import { ThemeConfig } from "antd";

export const ANT_CUSTOM_THEME: ThemeConfig = {
  // cssVar: true,
  token: {
    size: 14,
    borderRadius: 6,
    colorPrimary: "#7047EB",
    controlHeight: 40,
    fontWeightStrong: 700,
    fontSizeHeading1: 94,
    fontSizeHeading2: 58,
    fontSizeHeading3: 46,
    fontSizeHeading4: 34,
    fontSizeHeading5: 24,
    fontSizeLG: 20,
    fontSizeSM: 16,
    fontSizeXL: 24,
    lineHeight: 1.17,
    fontFamily: "'Kode Mono', monospace",
  },
  components: {
    Button: {
      colorBorder: "rgba(255, 255, 255, 0.20)",
      colorTextDisabled: "#F9FAFB",
      borderColorDisabled: "#8d6cef24",
      colorBgContainerDisabled: "#8d6cef24",
    },
    Input: {
      colorBorder: "rgba(255, 255, 255, 0.20)",
      colorText: "#F9FAFB",
    },
    Menu: {
      horizontalItemBorderRadius: 12,
    },
    Dropdown: {
      colorText: "#F9FAFB",
      colorIcon: "#F9FAFB",
      colorIconHover: "#F9FAFB",
      colorBgContainer: "#141127",
      colorBgTextActive: "#141127",
    },
    Table: {
      borderColor: "#a8a7af33",
      headerBg: "#141127",
      headerColor: "#6C6C89",
      borderRadius: 8,
      bodySortBg: "#141127",
      colorBgContainer: "#141127",
      colorText: "#F9FAFB",
      filterDropdownBg: "#141127",
      colorIcon: "#F9FAFB",
      colorIconHover: "#F9FAFB",
      rowSelectedBg: "#141127",
      filterDropdownMenuBg: "#141127",
      fixedHeaderSortActiveBg: "#141127",
      headerFilterHoverBg: "#141100",
      rowHoverBg: "transparent",
      headerSortActiveBg: "transparent",
    },
    Pagination: {
      itemBg: "#141127",
      colorIcon: "#F9FAFB",
      colorText: "#F9FAFB",
      colorIconHover: "#141127",
      colorInfoTextHover: "#141127",
      colorTextDisabled: "#707070",
      itemActiveBgDisabled: "#707070",
    },
    Steps: {
      colorIcon: "#F9FAFB",
      colorText: "#F9FAFB",
      colorTextDescription: "#cecece",
      colorTextDisabled: "#707070",
    }
  },
};
