export const CONTRACT_ADDRESS = '0x38bDa9F9bEF0C468f2E00E2B7892157fB6A249d5';
export const CONTRACT_METHOD_PLAYER_A_BET = 'betOnPlayerA';
export const CONTRACT_METHOD_PLAYER_B_BET = 'betOnPlayerB';
export const CONTRACT_METHOD_CLAIM_WINNINGS = 'claim';
